name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "1f197d921fa74019957f90ac798acc6a" },
  { binding = "SHARE", id = "1d6e22fecbe54394b22110e1bd40fb62" }
]